### ISSUE TITLE
Order projects alphabetically

### ISSUE THREAD

**Issue by ofek** [lk-geimfari/awesomo#101]
Based on https://github.com/lk-geimfari/awesomo/pull/98#issuecomment-329554698

- [x] C
- [x] C#
- [x] C++
- [x] Clojure
- [ ] Common Lisp
- [x] Crystal
- [x] CSS
- [ ] D 
- [x] Elixir
- [ ] Elm
- [x] Emacs Lisp
- [x] Erlang
- [ ] Go
- [x] Haskell
- [x] Java
- [x] JavaScript
- [ ] Lua
- [ ] Nim
- [ ] OCaml
- [ ] PHP
- [x] Python
- [ ] R
- [x] Ruby
- [x] Rust
- [ ] Scala
- [ ] Shell
- [x] SVG
- [x] Swift
- [x] TypeScript

**Comment by lk-geimfari** [comment]
@ofek Do you ordered this list manually or...?

**Comment by ofek** [comment]
Manually. yes.

**Comment by lk-geimfari** [comment]
If You are here on the Hacktoberfest, then I advise you to look at the list of projects in Python and use it as an example for the remaining lists of projects. Happy Hacktoberfest!

**Comment by biskit1** [comment]
Please make sure to add the letter 'O' to the table of contents at the top (copy the one from [c++](https://github.com/lk-geimfari/awesomo/blob/master/languages/C%2B%2B.md) after my [change]( is merged), and to double check that the project names are bolded (I found a few where the bolding was left out).
