### ISSUE TITLE
Automatically check last commit date.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/awesomo#139]
@makkoncept have created this [cool](https://gist.github.com/makkoncept/a4761815c67dfca5e6f109c11a9564bd) script for checking last commit date. I suggest to improve it and add to Travis CI.

**Comment by ad-m** [comment]
I suggest using this icon (badge), which will contain relevant information. A small script (ideal for hosting on AWS Lambda or other FaaS) that will accept the GitHub repository URL, retrieve information and redirect to the appropriate badge according to the ```https://img.shields.io/badge/<SUBJECT>-<STATUS>-<COLOR>.svg```.

**Comment by lk-geimfari** [comment]
@ad-m Sounds pretty cool.

**Comment by ad-m** [comment]
@lk-geimfari , i rewrited scripts above as NodeJS service as described in previous commend. Here is code: https://gist.github.com/ad-m/6c522dd3b96e38209a0c3f63cf317323
I don't have free time to host it anywhere in reliable way.

**Comment by makkoncept** [comment]
@lk-geimfari, can you look at it please !!

**Comment by lk-geimfari** [comment]
@makkoncept I don't know about node script, but the main idea is to use it on Travis. I think that Python script will much easy and lightweight.

**Comment by makkoncept** [comment]
@lk-geimfari I am not comfortable with node.js either. I agree with using Python for this task.
