### ISSUE TITLE
Update all the lists for all languages

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/awesomo#180]
Well, we need to check all the projects and remove outdated ones.

We declare this in the readme:

> However, keep in mind that we don't accept **mammoth's shit**. Only active and interesting projects with good documentation are added. Dead and abandoned projects will be removed.

But, sadly at this moment, this project looks like a mammoth shit itself.

We really need to fix it. I think we must remove all the outdated/unsupported/archived/deprecated projects from all the lists.

**Comment by lk-geimfari** [comment]
Any help would be useful.

**Comment by lk-geimfari** [comment]
@kaushalgautam Sure! Happy hacking for you!

**Comment by kaushalgautam** [comment]
@lk-geimfari **outdated/unsupported/archived/deprecated** is kinda subjective and vague, can we come up with some parameters for identifying the outdated projects? Or just go with intuition?

**Comment by lk-geimfari** [comment]
@kaushalgautam If a repository marked as an archived or it's informs that it's deprecated in README or in the description of the repository.

Or we can look at last commit date. If last commit was more than a year ago, so possibly project is not supported anymore.

**Comment by PandiyanCool** [comment]
Hi @lk-geimfari 

Can I take CSS part?

**Comment by lk-geimfari** [comment]
@PandiyanCool Sure you can!

**Comment by PandiyanCool** [comment]
> @PandiyanCool Hi! Sure you can!

This is done @lk-geimfari 🔥

**Comment by kaushalgautam** [comment]
> @kaushalgautam If a repository marked as an archived or it's informs that it's deprecated in README or in the description of the repository.
> 
> Or we can look at last commit date. If last commit was more than a year ago, so possibly project is not supported anymore.

These are the ones I feel can be removed. Most of them seem pretty dead to me. You may review them if your want: 

Code Surfer, 
Dillinger, 
Iroh, 
medium-editor
React-showroom
photoswipe

**Comment by lk-geimfari** [comment]
@kaushalgautam Great job! Let's create PR.

**Comment by kaushalgautam** [comment]
Done. I will let you know if I pick something else up. Thank you for letting me help @lk-geimfari 😄

**Comment by lk-geimfari** [comment]
@kaushalgautam Merged! Thank you for contributing and happy hacking!

**Comment by EdoRguez** [comment]
Hi, can I help you with C#?

**Comment by lk-geimfari** [comment]
@EdoRguez Hi! Sure you can!

**Comment by JeffUTF8** [comment]
Hello. Any chance that I could help with C++?

**Comment by A9u** [comment]
@lk-geimfari Hi, Can I help with Ruby?

**Comment by lk-geimfari** [comment]
@A9u Sure!

**Comment by dickyw71** [comment]
@lk-geimfari Hi, I will review the TypeScript project list.

**Comment by dickyw71** [comment]
@lk-geimfari The TypeScript list looks good to me. It could do with with some more projects. 
Is it OK to suggest more projects as a comment on this issue?

**Comment by dickyw71** [comment]
@lk-geimfari Looking through the Swift list.

**Comment by jrraymundo** [comment]
Hi! Would like to help update the list, and add an interesting project I know for Javascript

**Comment by dickyw71** [comment]
@lk-geimfari I think these projects can be removed as they look dead and have not been updated from more than a year.
OCAML : mldonkey
EMACS-Lisp : alchemist

ELM : https://github.com/elm-lang/http 
This repo is archived and has moved to:  https://github.com/elm/http

I can open a PR for these changes once you confirm.

**Comment by dickyw71** [comment]
@lk-geimfari I opened 2 PRs for the above.

**Comment by Ri2parna** [comment]
Can I help you with python ?

**Comment by lk-geimfari** [comment]
@Ri2parna Sure!

**Comment by mohdule** [comment]
Hey, i will be reviewing the JS list

**Comment by mohdule** [comment]
Hey !
I will be adding [React, Vue, Phaser, nsfwjs]
to the JS list

**Comment by lk-geimfari** [comment]
@mohdule Great!

**Comment by Whizkevina** [comment]
Is there any issue I can contribute to!

**Comment by lk-geimfari** [comment]
@Whizkevina You can change logo size of project for all lists.

**Comment by ilyaryabchinski** [comment]
Hi @lk-geimfari!
Could u plz check my PR #223  ?

**Comment by Whizkevina** [comment]
@lk-geimfari , I will..
Thanks for the opportunity!

**Comment by Whizkevina** [comment]
> @Whizkevina You can change the logo size of the projects in all lists.

What size should I make it.

**Comment by joekreydt** [comment]
If PR #229 is merged, that will clean up the Rust section.

**Comment by SanziSen** [comment]
Can I help you with C,CPP, Python?

**Comment by lk-geimfari** [comment]
@SanziSen Sure.

**Comment by MagnaibayarMN** [comment]
Hello. Can I take Golang section ?

**Comment by lk-geimfari** [comment]
@MagnaibayarMN Sure! Feel free to create PR with your changes.

**Comment by RupdeepDev** [comment]
@lk-geimfari I am updating the CSS part

**Comment by Ian-Yy** [comment]
Hi, I would like to take PHP section. Btw, I see only PHP Framework there. Is it just any PHP Library that's active and has great documentation makes into the list? How about WordPress?

**Comment by nobody5050** [comment]
hi, I would like to take a look at some JavaScript stuffs.

**Comment by bonniewhy** [comment]
I just submitted my first PR (ever) to update the Clojure list. Hope I did it right!

**Comment by lk-geimfari** [comment]
@bonniewhy Thank you! I have merged it.

**Comment by bonniewhy** [comment]
I have also cleaned up the Lua file (just for others to know who might be looking to contribute). If you want me to do more, let me know!

**Comment by lk-geimfari** [comment]
@bonniewhy I have merged it too. Thank you!

**Comment by abimbola001** [comment]
Hi, 
Please, I will like to contribute to this project. I can help with bash, python

**Comment by lk-geimfari** [comment]
@abimbola001 Hi! Thank you! I'll wait for your PR with changes.

**Comment by abimbola001** [comment]
Please what exactly do you want me to work on?

**Comment by lk-geimfari** [comment]
@abimbola001 We need to keep lists up-to-date, so the projects where the last commit was more than a year ago must be removed.

**Comment by abimbola001** [comment]
Noted. For example awesomo/languages/COMMON_LISP.md was last updated  in 2017

**Comment by lk-geimfari** [comment]
@abimbola001 Not really. It does not mean that the projects `COMMON_LISP ` contain was not updated since 2017.

**Comment by abimbola001** [comment]
what about awesomo/languages/SWIFT.md ?

**Comment by gioboa** [comment]
Hello. Can I take Java section ?

**Comment by lk-geimfari** [comment]
@gioboa Hi! Sure you can!

**Comment by reachananya** [comment]
Hey, Can I take  C language?

**Comment by lk-geimfari** [comment]
@reachananya Sure!

**Comment by Anish-M-code** [comment]
Hi @lk-geimfari  i have updated the python list and opened PR #342

**Comment by odi-adrianna** [comment]
@lk-geimfari Hi! I updated the JavaScript list - basically, the last repo changed the address - here's PR #426

**Comment by odi-adrianna** [comment]
@lk-geimfari I checked the CSS resources - they are all good and happy. Additionally, I added one resource for beginners - here's PR #427

**Comment by odi-adrianna** [comment]
@lk-geimfari Hi! I updated the CSS list - I added two new resources - here's PR #431
