### ISSUE TITLE
SweetAlert is not well-maintained

### ISSUE THREAD

**Issue by sallar** [lk-geimfari/awesomo#21]
Hi, 

SweetAlert (in JavaScript) section, is not a well maintained repo. The owner doesn't respond well to PRs. I checked and he has started accepting some pull requests, but I think it's a bit too late.

Someone has [Forked](https://github.com/limonte/sweetalert2) SweetAlert and it's in much better shape than the original, I suggest using and introducing that one instead.

**Comment by lk-geimfari** [comment]
@sallar Thanks. We fix it.

**Comment by sallar** [comment]
@lk-geimfari I can send a PR.

**Comment by lk-geimfari** [comment]
@sallar It's done! Check, please.

**Comment by sallar** [comment]
@lk-geimfari You're fast! Cheers.

**Comment by lk-geimfari** [comment]
@sallar Thanks!
