### ISSUE TITLE
Jekyll Static site for this repo

### ISSUE THREAD

**Issue by ram-nad** [lk-geimfari/awesomo#219]
:sparkles: It would be great if there could be a site for this repository. Jekyll could be easily used for this work. @lk-geimfari if you like this idea then I would be very happy to work on it.

**Comment by mokshchaudhary** [comment]
I would like to work on this

**Comment by lk-geimfari** [comment]
@ram-nad @mokshchaudhary I don't mind. You can collaborate to work on it together.

**Comment by mokshchaudhary** [comment]
I tried [Something](http://mokshchaudhary.github.io)
Fairly Crude Try.

![Screenshot from 2019-10-16 18-13-20](https://user-images.githubusercontent.com/17686504/66920371-c24e5f00-f040-11e9-806d-556c3b054463.png)

**Comment by ram-nad** [comment]
> I tried [Something](http://mokshchaudhary.github.io)
> Fairly Crude Try.
> 
> ![Screenshot from 2019-10-16 18-13-20](https://user-images.githubusercontent.com/17686504/66920371-c24e5f00-f040-11e9-806d-556c3b054463.png)

This is excellent. Sorry i was not available for the last few days. If any help is required i would be very happy to contribute.

**Comment by ram-nad** [comment]
@mokshchaudhary Could you please add `jemoji` & `github-pages` as a plugin in Gemfile?

**Comment by mokshchaudhary** [comment]
> There are some issues with some lists, for example, https://mokshchaudhary.github.io/go/

Yes  @lk-geimfari I'm looking into it

**Comment by mokshchaudhary** [comment]
### Made one using Gitbook.

https://moksh4445.gitbook.io/awesomo/

![Demo](https://i.imgur.com/UBNK40V.png)
