### ISSUE TITLE
PHP?

### ISSUE THREAD

**Issue by davidbarratt** [lk-geimfari/awesomo#23]
It would be great if you had a list for PHP.

**Comment by ad-m** [comment]
Whay do you want to list for PHP (except Faceboook of course) ?

**Comment by davidbarratt** [comment]
[Piwik](https://piwik.org/), [Drupal](http://drupal.org/), [WordPress](https://wordpress.org), [Symfony](http://symfony.com/), [phpBB](http://symfony.com/projects/phpbb), [Magento](https://magento.com/), [MediaWiki](https://www.mediawiki.org/wiki/MediaWiki), [Guzzle](http://docs.guzzlephp.org/), etc.

**Comment by lk-geimfari** [comment]
@davidbarratt I'm sorry, but it's all. PHP is not cool.

**Comment by deadcoder0904** [comment]
@lk-geimfari No offense... Its personal preference.... Some people still use it :smile: 
> There are only two kinds of languages: the ones people complain about and the ones nobody uses.
>  --- Bjarne Stroustrup

**Comment by lk-geimfari** [comment]
@deadcoder0904  Yeah, i know, but in open source `PHP` sucks. If you can find projects that is not a mammoth's shit in PHP, then i have nothing against.

**Comment by lk-geimfari** [comment]
@deadcoder0904 So, you can add PHP list if you will moderate it. Okay?

**Comment by deadcoder0904** [comment]
@lk-geimfari  Yaa but even I don't like `PHP` :joy: So if @davidbarratt wants to send a pull request, we'll merge it :smiley:

**Comment by lk-geimfari** [comment]
@deadcoder0904 @davidbarratt Sorry guys. I don't mean to offend you.

**Comment by deadcoder0904** [comment]
I have checked @davidbarratt Github Profile & he has lotta `PHP` knowledge so I think he can use his knowledge to send some `PHP` awesomo's. I'll moderate it :+1:  & @lk-geimfari I wasn't offended as I used to bitch about PHP but my friend does some awesome things with `PHP`

**Comment by lk-geimfari** [comment]
@deadcoder0904 That's a bargain!

**Comment by davidbarratt** [comment]
PHP has been my whole life. :)
I also have done a ton of Drupal work https://www.drupal.org/u/davidwbarratt

I think most of people's complaints (including my own) with PHP have been resolved since `5.3` when [Namespaces](http://php.net/manual/en/language.namespaces.rationale.php) and [Autoloading](http://php.net/manual/en/language.oop5.autoload.php) were introduced (save the inconsistent function naming/parameters).

These changes led to the [PHP Standards Recommendations](http://www.php-fig.org/psr/) and then [Composer](https://getcomposer.org/) which, imho, has made PHP cool again. :)

PHP [7.0](http://php.net/releases/7_0_0.php) is "up to twice as fast as PHP 5.6" so the complaint that it is slow isn't even valid anymore.

I'll send a PR in the near future! Thanks!

**Comment by deadcoder0904** [comment]
Keeping this open

**Comment by lk-geimfari** [comment]
@davidbarratt Thank you!

**Comment by capripot** [comment]
We could start the list and patch it #56

**Comment by dsslimshaddy** [comment]
lol
