### ISSUE TITLE
Add all the icons to a folder and make a them a standard size,quality,format

### ISSUE THREAD

**Issue by mokshchaudhary** [lk-geimfari/awesomo#245]
Right now all the icons have an external link which make them:

- Prone to change/deletion
- Different size,format and resolution
- Various images are transferred over HTTP instead of HTTPS (which might become a problem in future as more and more  browser start to block HTTP on HTTPS sites).
- External server might under-perform

My suggestion is to make a folder in the repository which has all the icons and images of the included libraries.

**Comment by lk-geimfari** [comment]
@mokshchaudhary I like this idea. Can you work on it?

**Comment by lk-geimfari** [comment]
@mokshchaudhary Let me add you to collaborators of this project.

**Comment by lk-geimfari** [comment]
@mokshchaudhary Please, accept an invite.

**Comment by mokshchaudhary** [comment]
@lk-geimfari I'd love to !

**Comment by bonniewhy** [comment]
I would love to help with this. Any further info on size, format, dimensions, etc to keep it uniform?

**Comment by lk-geimfari** [comment]
@mokshchaudhary Please, share with your view with @bonniewhy.
