### ISSUE TITLE
CSS?

### ISSUE THREAD

**Issue by deadcoder0904** [lk-geimfari/awesomo#25]
What do u think about CSS?? 
It has some really awesome projects like [Bootstrap](https://github.com/twbs/bootstrap), [Foundation](https://github.com/zurb/foundation-sites), [Pure](https://github.com/yahoo/pure), [Tachyons](https://github.com/tachyons-css/tachyons), [Post CSS](https://github.com/postcss/postcss) & many more...
What do u think @lk-geimfari ??

**Comment by lk-geimfari** [comment]
@deadcoder0904 I'm all for it.

**Comment by deadcoder0904** [comment]
Closing this. Check #27

**Comment by lk-geimfari** [comment]
@deadcoder0904 What would you say if I add you as a collaborator? You can moderate lists of JS and CSS.

**Comment by lk-geimfari** [comment]
@deadcoder0904 But never forget our main rules: [**We don't add to list mammoth's shit**](https://github.com/lk-geimfari/awesomo/blob/master/CONTRIBUTING.md)

**Comment by lk-geimfari** [comment]
@deadcoder0904 Now you can moderate `JS` and `CSS`. Others will moderate by myself.

**Comment by deadcoder0904** [comment]
Happy to do it :smile:

**Comment by lk-geimfari** [comment]
@deadcoder0904 Thank you!
