### ISSUE TITLE
Separate Common Lisp and Emacs Lisp by different files

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/awesomo#36]
Separate Common Lisp and Emacs Lisp by different files.

**Comment by lk-geimfari** [comment]
@deadcoder0904  Are you interested? Can you do it?

**Comment by deadcoder0904** [comment]
Nope don't know anything about `LISP`. Sorry :sob:

**Comment by lk-geimfari** [comment]
@deadcoder0904 It's okay. Not a problem.

**Comment by furkanusta** [comment]
I've checked LISP projects, and only Magit and Alchemist seems to in Emacs Lisp, which are both Emacs plugins. Moreover, other projects explicitly state in their description that they are Common Lisp Projects. 

I can send a PR to separate those two, but it would be nice if someone else double-checks as well

**Comment by lk-geimfari** [comment]
@furkanusta Thank you.

**Comment by lk-geimfari** [comment]
@furkanusta Add sections in README.md, please.
