### ISSUE TITLE
Can you add Java to the list

### ISSUE THREAD

**Issue by stenalpjolly** [lk-geimfari/awesomo#37]
Hi,
  I'm feeling that you guys left java along. Please Java Projects too...

**Comment by lk-geimfari** [comment]
@stenalpjolly I added [Java](https://github.com/lk-geimfari/awesomo/blob/master/languages/JAVA.md) to list. We will update list as soon as possible.

**Comment by lk-geimfari** [comment]
@stenalpjolly It's done!
