### ISSUE TITLE
Having C# projects would be nice

### ISSUE THREAD

**Issue by rblath** [lk-geimfari/awesomo#38]
I think C# is becoming a great language and should be mentioned in the list. Thanks.

**Comment by lk-geimfari** [comment]
@rblath They will soon.

**Comment by shahid-pk** [comment]
i will suggest ....
https://github.com/NancyFx/Nancy
https://github.com/dotnet/corefx
https://github.com/dotnet/roslyn
https://github.com/Azure/DotNetty
https://github.com/cake-build/cake
https://github.com/opentk/opentk
https://github.com/nunit/nunit
https://github.com/ravendb/ravendb

**Comment by lk-geimfari** [comment]
@shahid-pk Good list. I will add all.
