### ISSUE TITLE
Generate lists dynamically, based on JSON file

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/awesomo#402]
We'll create a JSON file with following structure:

```json
[
  {
    "language": "C",
    "projects": [
      {
        "name": "Project",
        "description": "Description",
        "url": "https://github.com/user/repository",
        "image_url": "https://example.org/example.png"
      },
      {
        "name": "Project 2",
        "description": "Description 2",
        "url": "https://github.com/user/repository",
        "image_url": "https://example.org/example.png"
      }
    ]
  },
  {
    "language": "C++",
    "projects": [
      {
        "name": "Project",
        "description": "Description",
        "url": "https://github.com/user/repository",
        "image_url": "https://example.org/example.png"
      }
    ]
  }
]

```

based on which all the lists of projects will be generated (using Github Actions).

**Comment by G0maa** [comment]
I'm _very_ new to open-source contribution, so bear with me : )

So provided `.JSON` file of the projects, the `action` will basically re-create `/languages` folder?

**Comment by lk-geimfari** [comment]
> I'm _very_ new to open-source contribution, so bear with me : )
> 
> So provided `.JSON` file of the projects, the `action` will basically re-create `/languages` folder?

Right!

**Comment by G0maa** [comment]
Ok I'll try playing around it for a bit... does the `.JSON` file of all existing projects in `/languages` exist or is that a sub-task within the issue? 👀

**Comment by G0maa** [comment]
Ok, I played a bit with it, see: https://github.com/G0maa/awesomo/tree/testing-script

Since there'd be lots of non-needed commits (because of testing workflow) I will create another branch and PR it, if the current solution passes.
@lk-geimfari

**Comment by G0maa** [comment]
@lk-geimfari Hello?

**Comment by Zireael07** [comment]
Closed as completed? Was it really done?
