### ISSUE TITLE
C and C++ should not be lumped together

### ISSUE THREAD

**Issue by tcbrindle** [lk-geimfari/awesomo#42]
C and C++ are different languages, and people who are interested in working in one are rarely interested in working in the other. They should have separate entries in the list.

**Comment by lk-geimfari** [comment]
@tcbrindle Yes, you right. If you can do it right now, then i accept your PR without any questions, but if you're cannot, then  i separate them as soon as it possible.

**Comment by lk-geimfari** [comment]
@tcbrindle It's done!
