### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by simondel** [lk-geimfari/awesomo#48]
There are some great TypeScript projects on GitHub, I think they should be added to this repo! Are you open to a PR?

Some repo's I'm thinking about: [TypeScript](https://github.com/Microsoft/TypeScript), [Visual Studio Code](https://github.com/Microsoft/vscode), [Ionic](https://github.com/driftyco/ionic), [Stryker](https://github.com/stryker-mutator/stryker), [Angular](https://github.com/angular/angular), [Angular Material](https://github.com/angular/material2)

**Comment by lk-geimfari** [comment]
@simondel Not a problem. Send us PR.

**Comment by lk-geimfari** [comment]
@deadcoder0904 Hi! TypeScript is for you. Can you follow with this list too?

**Comment by deadcoder0904** [comment]
Thanx :smile: But, actually I am React guy so haven't used `TypeScript` (used to ES6+). So, I can review if u want

**Comment by lk-geimfari** [comment]
@deadcoder0904 I know nothing in front-end. And in languages as `SomethingScript`. Thank you.

**Comment by deadcoder0904** [comment]
Alright :+1:  But, no wonder how you created this `awesomo` project :clap: Cheers to that :clinking_glasses:
