### ISSUE TITLE
Add more C/C++ projects

### ISSUE THREAD

**Issue by Randl** [lk-geimfari/awesomo#59]
[LLVM](https://github.com/llvm-mirror/llvm), [tox](https://github.com/TokTok/c-toxcore) , [veracrypt](https://github.com/veracrypt/VeraCrypt) , [OpenCV](https://github.com/opencv/opencv) , [i2pd](https://github.com/PurpleI2P/i2pd) , [Tensorflow](https://github.com/tensorflow/tensorflow) , [Tesseract](https://github.com/tesseract-ocr/tesseract) , [ArangoDB](https://github.com/arangodb/arangodb) , [libcds](https://github.com/khizmax/libcds)

**Comment by lk-geimfari** [comment]
@Randl Send us PR, please.
