### ISSUE TITLE
Center all images for all lists.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/awesomo#69]
We need to center all images for all list. Also we need to change sizes of images all images must be the same size.

**Comment by lk-geimfari** [comment]
@deadcoder0904 Can you do this for JS list?

**Comment by deadcoder0904** [comment]
Can't do it now as I'm working on another project which might take atleast a month's time

**Comment by lk-geimfari** [comment]
@deadcoder0904 Oh, sorry. It's not a problem. Thank you!
