### ISSUE TITLE
Collaborators for lists.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/awesomo#71]
We need more people who will track the lists for different programming languages.

Please, write us if you have experience in one of the listed [languages](https://github.com/lk-geimfari/awesomo#languages) want to help made this list better. We can do it only together. 

Thanks.

At this moment:

- @deadcoder0904 -> (JS, CSS, TypeScript)
- @TrueFurby -> Golang

**Comment by lk-geimfari** [comment]
@Battleroid, @wikkiewikkie I added you as collaborators. Feel free to add new cool projects to list, guys. Thanks you.

**Comment by caspian-seagull** [comment]
✌

**Comment by ertugrulcetin** [comment]
That's cool thanks!

**Comment by Battleroid** [comment]
Cool, thank you.

**Comment by sopanhavuth-aka-sam** [comment]
I dont have much experience with open source yet. But currently I'm browsing around to find beginner friendly project that I can contribute to. I can add what I found to this project. I mostly focus on Java and automation testing.
Thanks. :)

**Comment by lk-geimfari** [comment]
@sopanhavuth-aka-sam Now you are collaborator of this list.

**Comment by sopanhavuth-aka-sam** [comment]
@lk-geimfari Since I'm a collaborator now, should I push directly to master? or should I stick to making pull request? I'm new to open source.
Thanks. :)

**Comment by lk-geimfari** [comment]
@sopanhavuth-aka-sam Just follow our guidelines and you can push to master. It's not a problem. Thank you!

**Comment by lk-geimfari** [comment]
@sopanhavuth-aka-sam Also you can merge PRs, but keep in mind that we do not add old and inactive projects to list.
