### ISSUE TITLE
Usage of South Park character Copyright

### ISSUE THREAD

**Issue by 64b2b6d12b** [lk-geimfari/awesomo#81]
Is the usage of the [South Park character](https://github.com/lk-geimfari/awesomo/blob/master/artwork/a.w.e.s.o.m.e_o.png) not an infringement of [South Park Terms of Use](http://southpark.cc.com/about/legal/terms-of-use)?

**Comment by lk-geimfari** [comment]
@64b2b6d12b I hope that not, because we are not commercial community. We do not sell anything, but if it infringement anything then i'll remove logo and replace it with other.
